// Error Handling
console.log('Before Error');

/*  try{
    test()

 } catch(err){
    console.log(err.message)
 }
console.log('After Error')
 */

// Rest Operators
/* let num = [12, 23, 24]
let test = (name, ...numbers)=>{ // rest 
    console.log(name)
    console.log(numbers)
}
test("Tushar", 32,23,24)
test("Gaus", ...num) // Spread */